"""Log computed analysis data to W&B for interactive visualization in reports.

Creates a lightweight W&B run (job_type='mcp-analysis', tagged 'mcp-generated'),
logs wandb.Table + wandb.plot charts + scalar metrics, returns run_id for use
in create_wandb_report_tool panels.
"""

from typing import Any, Dict, List, Optional

import wandb

from wandb_mcp_server.api_client import WandBApiManager
from wandb_mcp_server.config import WANDB_BASE_URL
from wandb_mcp_server.mcp_tools.tools_utils import log_tool_call
from wandb_mcp_server.utils import get_rich_logger

logger = get_rich_logger(__name__)


LOG_ANALYSIS_TOOL_DESCRIPTION = """Log computed analysis data to W&B for interactive visualization in reports.

<when_to_use>
Call this BEFORE create_wandb_report_tool when you have computed data
(latency distributions, error breakdowns, custom aggregations) that
you want to visualize as interactive charts in a W&B report.

Typical workflow:
1. Query data with query_weave_traces_tool or query_wandb_tool
2. Compute analysis (percentiles, distributions, aggregations) in code
3. Call log_analysis_to_wandb with the computed data
4. Call create_wandb_report_tool referencing the returned run_id in panels
</when_to_use>

The tool creates a lightweight W&B run (tagged 'mcp-generated',
job_type='mcp-analysis') and logs:
- A wandb.Table with all your data (sortable/filterable in W&B UI)
- Interactive charts (histogram, bar, scatter, line) from the table
- Scalar summary metrics (p50, p95, etc.)

Parameters
----------
entity_name : str
    The W&B entity (team or username).
project_name : str
    The W&B project name.
analysis_name : str
    Display name for the analysis run (e.g., "latency-analysis-2026-03-27").
data : list of dict
    Rows of computed data. Each dict is a row with consistent keys.
    Example: [{"trace_id": "abc", "latency_ms": 1234, "status": "success"}, ...]
charts : list of dict, optional
    Chart specifications to create from the data table:
    - {"type": "histogram", "column": "latency_ms", "title": "Latency Distribution"}
    - {"type": "bar", "label": "status", "value": "count", "title": "Status Breakdown"}
    - {"type": "scatter", "x": "latency_ms", "y": "token_count", "title": "Latency vs Tokens"}
    - {"type": "line", "x": "timestamp", "y": "latency_ms", "title": "Latency Over Time"}
scalars : dict, optional
    Scalar summary metrics to log. Example: {"p50_latency_ms": 1.2, "p95_latency_ms": 4.5}

Returns
-------
JSON with run_id, run_url, and logged metric keys. Pass run_id to
create_wandb_report_tool panels using the analysis_run_id field.

Example
-------
>>> result = log_analysis_to_wandb(
...     entity_name="my-team",
...     project_name="my-project",
...     analysis_name="latency-analysis",
...     data=[{"op": "predict", "latency_ms": 120}, {"op": "predict", "latency_ms": 450}],
...     charts=[{"type": "histogram", "column": "latency_ms", "title": "Latency"}],
...     scalars={"p50_latency_ms": 285, "mean_latency_ms": 285}
... )
>>> # Then in create_wandb_report_tool:
>>> # panels=[{"type": "line", "x": "_step", "y": ["p50_latency_ms"], "analysis_run_id": result["run_id"]}]
"""


def log_analysis(
    entity_name: str,
    project_name: str,
    analysis_name: str,
    data: List[Dict[str, Any]],
    charts: Optional[List[Dict[str, Any]]] = None,
    scalars: Optional[Dict[str, float]] = None,
) -> Dict[str, Any]:
    """Log computed analysis data to W&B."""
    api_key = WandBApiManager.get_api_key()
    if not api_key:
        raise Exception("No W&B API key available")

    try:
        api = WandBApiManager.get_api()
        log_tool_call(
            "log_analysis_to_wandb",
            api.viewer,
            {
                "entity_name": entity_name,
                "project_name": project_name,
                "analysis_name": analysis_name,
                "row_count": len(data),
                "chart_count": len(charts or []),
                "scalar_count": len(scalars or {}),
            },
        )
    except Exception:
        logger.debug("analytics emit failed", exc_info=True)

    if not data:
        raise ValueError("data must be a non-empty list of dicts")

    run = wandb.init(
        entity=entity_name,
        project=project_name,
        name=analysis_name,
        job_type="mcp-analysis",
        tags=["mcp-generated"],
        notes="Auto-generated by W&B MCP Server",
        settings=wandb.Settings(
            api_key=api_key,
            base_url=WANDB_BASE_URL,
            silent=True,
        ),
    )

    try:
        columns = list(data[0].keys())
        table = wandb.Table(
            columns=columns,
            data=[[row.get(k) for k in columns] for row in data],
        )

        log_payload: Dict[str, Any] = {"analysis_data": table}

        if scalars:
            log_payload.update(scalars)

        if charts:
            for i, spec in enumerate(charts):
                chart_type = spec.get("type", "")
                title = spec.get("title", f"Chart {i + 1}")
                try:
                    if chart_type == "histogram":
                        log_payload[f"chart_{i}"] = wandb.plot.histogram(table, spec["column"], title=title)
                    elif chart_type == "bar":
                        log_payload[f"chart_{i}"] = wandb.plot.bar(table, spec["label"], spec["value"], title=title)
                    elif chart_type == "scatter":
                        log_payload[f"chart_{i}"] = wandb.plot.scatter(table, spec["x"], spec["y"], title=title)
                    elif chart_type == "line":
                        log_payload[f"chart_{i}"] = wandb.plot.line(table, spec["x"], spec["y"], title=title)
                    else:
                        logger.warning(f"Unknown chart type: {chart_type}")
                except Exception as e:
                    logger.warning(f"Failed to create chart '{title}': {e}")

        wandb.log(log_payload)
        run_id = run.id
        run_url = run.url

    finally:
        run.finish()

    logger.info(f"Logged analysis '{analysis_name}' to run {run_id}")

    return {
        "run_id": run_id,
        "run_url": run_url,
        "logged_keys": list(log_payload.keys()),
        "table_columns": columns,
        "row_count": len(data),
    }
