"""Log computed analysis data to W&B for visualization in reports.

Creates a lightweight W&B run via the PublicApi (no wandb.init()),
logs scalar summary metrics via GraphQL UpsertBucket, and returns
the run_id for use in create_wandb_report_tool panels.

Security: Uses wandb.Api(api_key=...) per-request, same pattern as
every other tool. No global state, no wandb.init(), no background
processes, no disk artifacts beyond a temp directory.
"""

import json
from typing import Any, Dict, List, Optional

import wandb

from wandb_mcp_server.api_client import WandBApiManager
from wandb_mcp_server.config import WANDB_BASE_URL
from wandb_mcp_server.mcp_tools.tools_utils import track_tool_execution
from wandb_mcp_server.utils import get_rich_logger

logger = get_rich_logger(__name__)


LOG_ANALYSIS_TOOL_DESCRIPTION = """Log computed analysis data to W&B for visualization in reports.

<when_to_use>
Call this BEFORE create_wandb_report_tool when you have computed data
(latency distributions, error breakdowns, custom aggregations) that
you want to persist as a W&B run with summary metrics.

Typical workflow:
1. Query data with query_weave_traces_tool or query_wandb_tool
2. Compute analysis (percentiles, distributions, aggregations) in code
3. Call log_analysis_to_wandb with the computed data and scalar summaries
4. Call create_wandb_report_tool referencing the returned run_id in panels
</when_to_use>

The tool creates a lightweight W&B run (tagged 'mcp-generated',
job_type='mcp-analysis') and logs scalar summary metrics to it.
Numeric columns in the data are auto-summarized (mean, min, max, median).

For structured tabular data in reports, use the markdown_table panel type
in create_wandb_report_tool. For custom visualizations, use SVG via the
plots_html parameter.

Parameters
----------
entity_name : str
    The W&B entity (team or username).
project_name : str
    The W&B project name.
analysis_name : str
    Display name for the analysis run (e.g., "latency-analysis-2026-03-27").
data : list of dict
    Rows of computed data. Each dict is a row with consistent keys.
    Numeric columns are auto-summarized (mean, min, max, median).
    Example: [{"trace_id": "abc", "latency_ms": 1234, "status": "success"}, ...]
scalars : dict, optional
    Explicit scalar summary metrics to log.
    Example: {"p50_latency_ms": 1.2, "p95_latency_ms": 4.5, "error_rate": 0.03}

Returns
-------
JSON with run_id, run_url, and logged metric keys. Pass run_id to
create_wandb_report_tool panels using the analysis_run_id field.

Example
-------
>>> result = log_analysis_to_wandb(
...     entity_name="my-team",
...     project_name="my-project",
...     analysis_name="latency-analysis",
...     data=[{"op": "predict", "latency_ms": 120}, {"op": "predict", "latency_ms": 450}],
...     scalars={"p50_latency_ms": 285, "mean_latency_ms": 285}
... )
>>> # Then in create_wandb_report_tool:
>>> # panels=[{"type": "bar", "metrics": ["p50_latency_ms"], "analysis_run_id": result["run_id"]}]
"""


def log_analysis(
    entity_name: str,
    project_name: str,
    analysis_name: str,
    data: List[Dict[str, Any]],
    charts: Optional[List[Dict[str, Any]]] = None,
    scalars: Optional[Dict[str, float]] = None,
) -> Dict[str, Any]:
    """Log computed analysis data to W&B via the PublicApi.

    Uses wandb.Api(api_key=...) for safe multi-tenant operation.
    No wandb.init(), no global state, no background processes.
    """
    api_key = WandBApiManager.get_api_key()
    if not api_key:
        raise Exception("No W&B API key available")

    api = WandBApiManager.get_api()
    with track_tool_execution(
        "log_analysis_to_wandb",
        api.viewer,
        {
            "entity_name": entity_name,
            "project_name": project_name,
            "analysis_name": analysis_name,
            "row_count": len(data),
            "scalar_count": len(scalars or {}),
        },
    ):
        if not data:
            raise ValueError("data must be a non-empty list of dicts")

        wandb_api = wandb.Api(api_key=api_key, overrides={"base_url": WANDB_BASE_URL})
        run = wandb_api.create_run(entity=entity_name, project=project_name)

        try:
            # wandb SDK bug: create_run() returns a Run missing .group,
            # which run.update() internally reads. Pre-initialize it.
            run.group = ""
            run.tags = ["mcp-generated"]
            run.job_type = "mcp-analysis"
            run.display_name = analysis_name
            run.notes = "Auto-generated by W&B MCP Server"

            summary_data: Dict[str, Any] = {}
            if scalars:
                summary_data.update(scalars)

            columns = list(data[0].keys())
            summary_data["_mcp_row_count"] = len(data)
            summary_data["_mcp_columns"] = json.dumps(columns)

            for key in columns:
                values = [r.get(key) for r in data if isinstance(r.get(key), (int, float))]
                if len(values) >= 2:
                    sorted_vals = sorted(values)
                    summary_data[f"{key}_mean"] = sum(values) / len(values)
                    summary_data[f"{key}_min"] = sorted_vals[0]
                    summary_data[f"{key}_max"] = sorted_vals[-1]
                    mid = len(sorted_vals) // 2
                    summary_data[f"{key}_median"] = sorted_vals[mid]

            if summary_data:
                run.summary.update(summary_data)

            run.update()

        except Exception as e:
            logger.error(f"Failed to update analysis run: {e}", exc_info=True)
            raise

        run_id = run.id
        run_url = f"https://wandb.ai/{entity_name}/{project_name}/runs/{run_id}"

        logger.info(f"Logged analysis '{analysis_name}' to run {run_id}")

        return {
            "run_id": run_id,
            "run_url": run_url,
            "logged_keys": list(summary_data.keys()),
            "table_columns": columns,
            "row_count": len(data),
        }
